export enum actionTypes {
  AUTH_ERROR = 'AUTH_ERROR',
  AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR',
  AUTH_LOADING = 'AUTH_LOADING',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_CLEAR_STATE = 'AUTH_CLEAR_STATE',
}
